/* 
 * EpsilonSmart Eshop API
 *
 * This is the EspilonSmart API descriptor. The particular definition of the API provides API endpoints related to e-shop operations. </br>  All the following actions require Authorization token. Http request should contain a header having key: 'Authorization' and value: 'Bearer {Jwt Token value}'.   If the request lacks Authorization header or the token is invalid, each action responds with status 401 Unauthorized.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using epsilonSmart.eShopApi.Client;
using epsilonSmart.eShopApi.Api;
using epsilonSmart.eShopApi.Models;

namespace epsilonSmart.eShopApi.Test
{
    /// <summary>
    ///  Class for testing MiEshopAPIApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class MiEshopAPIApiTests
    {
        private MiEshopAPIApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new MiEshopAPIApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MiEshopAPIApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' MiEshopAPIApi
            //Assert.IsInstanceOfType(typeof(MiEshopAPIApi), instance, "instance is a MiEshopAPIApi");
        }

        /// <summary>
        /// Test ApiEshopGetItemsGet
        /// </summary>
        [Test]
        public void ApiEshopGetItemsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? revisionNumber = null;
            //var response = instance.ApiEshopGetItemsGet(revisionNumber);
            //Assert.IsInstanceOf<List<EshopItem>> (response, "response is List<EshopItem>");
        }
        /// <summary>
        /// Test ApiEshopInsertDocumentsPost
        /// </summary>
        [Test]
        public void ApiEshopInsertDocumentsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<EshopSale> body = null;
            //instance.ApiEshopInsertDocumentsPost(body);
            
        }
    }

}
