/* 
 * EpsilonSmart Eshop API
 *
 * This is the EspilonSmart API descriptor. The particular definition of the API provides API endpoints related to e-shop operations. </br>  All the following actions require Authorization token. Http request should contain a header having key: 'Authorization' and value: 'Bearer {Jwt Token value}'.   If the request lacks Authorization header or the token is invalid, each action responds with status 401 Unauthorized.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using epsilonSmart.eShopApi.Api;
using epsilonSmart.eShopApi.Models;
using epsilonSmart.eShopApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace epsilonSmart.eShopApi.Test
{
    /// <summary>
    ///  Class for testing EshopItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EshopItemTests
    {
        // TODO uncomment below to declare an instance variable for EshopItem
        //private EshopItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EshopItem
            //instance = new EshopItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EshopItem
        /// </summary>
        [Test]
        public void EshopItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EshopItem
            //Assert.IsInstanceOfType<EshopItem> (instance, "variable 'instance' is a EshopItem");
        }


        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Test]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'ScanCode'
        /// </summary>
        [Test]
        public void ScanCodeTest()
        {
            // TODO unit test for the property 'ScanCode'
        }
        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Test]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }
        /// <summary>
        /// Test the property 'NormalVATPercent'
        /// </summary>
        [Test]
        public void NormalVATPercentTest()
        {
            // TODO unit test for the property 'NormalVATPercent'
        }
        /// <summary>
        /// Test the property 'ReducedVATPercent'
        /// </summary>
        [Test]
        public void ReducedVATPercentTest()
        {
            // TODO unit test for the property 'ReducedVATPercent'
        }
        /// <summary>
        /// Test the property 'MeasurementUnit'
        /// </summary>
        [Test]
        public void MeasurementUnitTest()
        {
            // TODO unit test for the property 'MeasurementUnit'
        }
        /// <summary>
        /// Test the property 'MeasurementUnitShortcut'
        /// </summary>
        [Test]
        public void MeasurementUnitShortcutTest()
        {
            // TODO unit test for the property 'MeasurementUnitShortcut'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'RetailCategory'
        /// </summary>
        [Test]
        public void RetailCategoryTest()
        {
            // TODO unit test for the property 'RetailCategory'
        }
        /// <summary>
        /// Test the property 'RetailCategoryInnerCode'
        /// </summary>
        [Test]
        public void RetailCategoryInnerCodeTest()
        {
            // TODO unit test for the property 'RetailCategoryInnerCode'
        }
        /// <summary>
        /// Test the property 'WholesalePrice'
        /// </summary>
        [Test]
        public void WholesalePriceTest()
        {
            // TODO unit test for the property 'WholesalePrice'
        }
        /// <summary>
        /// Test the property 'RetailPrice'
        /// </summary>
        [Test]
        public void RetailPriceTest()
        {
            // TODO unit test for the property 'RetailPrice'
        }
        /// <summary>
        /// Test the property 'Remarks'
        /// </summary>
        [Test]
        public void RemarksTest()
        {
            // TODO unit test for the property 'Remarks'
        }
        /// <summary>
        /// Test the property 'UserDefinedText01'
        /// </summary>
        [Test]
        public void UserDefinedText01Test()
        {
            // TODO unit test for the property 'UserDefinedText01'
        }
        /// <summary>
        /// Test the property 'UserDefinedText02'
        /// </summary>
        [Test]
        public void UserDefinedText02Test()
        {
            // TODO unit test for the property 'UserDefinedText02'
        }
        /// <summary>
        /// Test the property 'UserDefinedText03'
        /// </summary>
        [Test]
        public void UserDefinedText03Test()
        {
            // TODO unit test for the property 'UserDefinedText03'
        }
        /// <summary>
        /// Test the property 'UserDefinedText04'
        /// </summary>
        [Test]
        public void UserDefinedText04Test()
        {
            // TODO unit test for the property 'UserDefinedText04'
        }
        /// <summary>
        /// Test the property 'UserDefinedText05'
        /// </summary>
        [Test]
        public void UserDefinedText05Test()
        {
            // TODO unit test for the property 'UserDefinedText05'
        }
        /// <summary>
        /// Test the property 'RevisionNumber'
        /// </summary>
        [Test]
        public void RevisionNumberTest()
        {
            // TODO unit test for the property 'RevisionNumber'
        }

    }

}
