/* 
 * EpsilonSmart Eshop API
 *
 * This is the EspilonSmart API descriptor. The particular definition of the API provides API endpoints related to e-shop operations. </br>  All the following actions require Authorization token. Http request should contain a header having key: 'Authorization' and value: 'Bearer {Jwt Token value}'.   If the request lacks Authorization header or the token is invalid, each action responds with status 401 Unauthorized.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using epsilonSmart.eShopApi.Api;
using epsilonSmart.eShopApi.Models;
using epsilonSmart.eShopApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace epsilonSmart.eShopApi.Test
{
    /// <summary>
    ///  Class for testing EshopSale
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EshopSaleTests
    {
        // TODO uncomment below to declare an instance variable for EshopSale
        //private EshopSale instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EshopSale
            //instance = new EshopSale();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EshopSale
        /// </summary>
        [Test]
        public void EshopSaleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EshopSale
            //Assert.IsInstanceOfType<EshopSale> (instance, "variable 'instance' is a EshopSale");
        }


        /// <summary>
        /// Test the property 'DocDateTime'
        /// </summary>
        [Test]
        public void DocDateTimeTest()
        {
            // TODO unit test for the property 'DocDateTime'
        }
        /// <summary>
        /// Test the property 'IsRetail'
        /// </summary>
        [Test]
        public void IsRetailTest()
        {
            // TODO unit test for the property 'IsRetail'
        }
        /// <summary>
        /// Test the property 'VatStatus'
        /// </summary>
        [Test]
        public void VatStatusTest()
        {
            // TODO unit test for the property 'VatStatus'
        }
        /// <summary>
        /// Test the property 'RefDocCode'
        /// </summary>
        [Test]
        public void RefDocCodeTest()
        {
            // TODO unit test for the property 'RefDocCode'
        }
        /// <summary>
        /// Test the property 'DocNum'
        /// </summary>
        [Test]
        public void DocNumTest()
        {
            // TODO unit test for the property 'DocNum'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Test]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'PaymentCreditCardName'
        /// </summary>
        [Test]
        public void PaymentCreditCardNameTest()
        {
            // TODO unit test for the property 'PaymentCreditCardName'
        }
        /// <summary>
        /// Test the property 'PaymentBankAccName'
        /// </summary>
        [Test]
        public void PaymentBankAccNameTest()
        {
            // TODO unit test for the property 'PaymentBankAccName'
        }
        /// <summary>
        /// Test the property 'CustName'
        /// </summary>
        [Test]
        public void CustNameTest()
        {
            // TODO unit test for the property 'CustName'
        }
        /// <summary>
        /// Test the property 'CustTIN'
        /// </summary>
        [Test]
        public void CustTINTest()
        {
            // TODO unit test for the property 'CustTIN'
        }
        /// <summary>
        /// Test the property 'CustStreet'
        /// </summary>
        [Test]
        public void CustStreetTest()
        {
            // TODO unit test for the property 'CustStreet'
        }
        /// <summary>
        /// Test the property 'CustStreet'
        /// </summary>
        [Test]
        public void CustStreetTest()
        {
            // TODO unit test for the property 'CustStreet'
        }
        /// <summary>
        /// Test the property 'CustCity'
        /// </summary>
        [Test]
        public void CustCityTest()
        {
            // TODO unit test for the property 'CustCity'
        }
        /// <summary>
        /// Test the property 'CustPostalCode'
        /// </summary>
        [Test]
        public void CustPostalCodeTest()
        {
            // TODO unit test for the property 'CustPostalCode'
        }
        /// <summary>
        /// Test the property 'CustCountry'
        /// </summary>
        [Test]
        public void CustCountryTest()
        {
            // TODO unit test for the property 'CustCountry'
        }
        /// <summary>
        /// Test the property 'CustEmail'
        /// </summary>
        [Test]
        public void CustEmailTest()
        {
            // TODO unit test for the property 'CustEmail'
        }
        /// <summary>
        /// Test the property 'CustPhone1'
        /// </summary>
        [Test]
        public void CustPhone1Test()
        {
            // TODO unit test for the property 'CustPhone1'
        }
        /// <summary>
        /// Test the property 'ExtraCharges'
        /// </summary>
        [Test]
        public void ExtraChargesTest()
        {
            // TODO unit test for the property 'ExtraCharges'
        }
        /// <summary>
        /// Test the property 'Justification'
        /// </summary>
        [Test]
        public void JustificationTest()
        {
            // TODO unit test for the property 'Justification'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'UserDefText01'
        /// </summary>
        [Test]
        public void UserDefText01Test()
        {
            // TODO unit test for the property 'UserDefText01'
        }
        /// <summary>
        /// Test the property 'UserDefText02'
        /// </summary>
        [Test]
        public void UserDefText02Test()
        {
            // TODO unit test for the property 'UserDefText02'
        }
        /// <summary>
        /// Test the property 'UserDefText03'
        /// </summary>
        [Test]
        public void UserDefText03Test()
        {
            // TODO unit test for the property 'UserDefText03'
        }
        /// <summary>
        /// Test the property 'UserDefText04'
        /// </summary>
        [Test]
        public void UserDefText04Test()
        {
            // TODO unit test for the property 'UserDefText04'
        }
        /// <summary>
        /// Test the property 'UserDefText05'
        /// </summary>
        [Test]
        public void UserDefText05Test()
        {
            // TODO unit test for the property 'UserDefText05'
        }
        /// <summary>
        /// Test the property 'Lines'
        /// </summary>
        [Test]
        public void LinesTest()
        {
            // TODO unit test for the property 'Lines'
        }

    }

}
